const fs = require('fs');

const rawCsv = `
Tibetan Name (Original),File Number,English Name,Status, Section ,,,
 ༤།༡ ཆོས་ཁོངས་ཆོས་དང་རིག་ཞུང་་ཚོགས་པ། , 4|1 ,Department of Religion & Culture,Active, Head Office ,,,
 ༤།༢ བོད་ཀྱི་དཔེ་མཛོད་ཁང་། , 4|2 ,Library of Tibetan Works and Archives (LTWA),Active, Head Office ,,,
 ༤།༣ ཤེས་རིག་ལས་ཁུངས་དང་ཁྱབ་ཁོངས། , 4|3 ,Department of Education,Active, Head Office ,,,
 ༤།༣(ཀ) སམ་བྷོ་ཊ་སྤྱི་ཁྱབ་ཡིག་ཚང་། , 4|3 A ,STSS Head Office,Active, Head Office ,,,
 ༤།༡༡ ཤེས་རིག་དཔར་ཁང་མ་ལག , 4|11 ,Sherig Parkhang,Active, Head Office ,,,
 ༤།༡༢ རྡ་ས་བོད་ཕྲུག་ཁྱིམ་སྡེ་དབུས་སྤྱི་ཁྱབ་ལས་ཁང་། , 4|12 ,TCV Head Office,Active, Head Office ,,,
 ༤།༡༣ རྡ་ས་བོད་ཁྱིམ་ལག་ཤེས་བཟོ་གྲྭ། , 4|13 ,TCV Handicraft-Cum-Vocational Traning Centre,Active, Head Office ,,,
 ༤།༡༥ ཕྱི་དྲིལ་ལས་ཁུངས། , 4|15 ,Department of Information and International Relations (DIIR),Active, Head Office ,,,
 ༤།༢༥ རྡ་ས་བོད་ཀྱི་གསོལ་མགྲོན་ཁང་། , 4|25 ,Hotel Tibet Dharamshala ,Active, Head Office ,,,
 ༤།༢༩ འཕྲོད་བསྟེན་ལས་ཁུངས་། , 4|29 ,Department of Health,Active, Head Office ,,,
 ༤།༣༠ བདེ་ལེགས་སྨན་ཁང་། , 4|30 ,Delek Hospital,Active, Head Office ,,,
 ༤།༣༡ སྨན་རྩིས་ཁང་དབུས་དང་ལྡི་ལི་ཕྱི་ཚོང་ཁང་། , 4|31 ,Mentsekhang Head Office,Active, Head Office ,,,
, 4|31 A ,Mentsekhang Branches (Under Head Office),Active, Head Office ,,,
, 4|31 B ,Mentsekhang HPRD,Active, Head Office ,,,
, 4|31 C ,Mentsekhang Menzoe (Medicine Godown),Active, Head Office ,,,
, 4|31 D ,Mentsekhang Pharmacy,Active, Head Office ,,,
 ༤།༤༠ རྩིས་ཞིབ་ལས་ཁང་། , 4|40 ,Office of Auditor General,Active, Head Office ,,,
 ༤།༤༡ རྡ་ཤོད་བོད་ཁྱིམ་སློབ་གྲྭ། , 4|41 ,Lower TCV School,Active, Head Office ,,,
 ༤།༤༤ ནང་སྲིད་ལས་ཁུངས་ཀྱི་དབུས་ངལ་སེལ་ཚོགས་པ། , 4|44 ,Department of Home,Active, Head Office ,,,
 ༤།༤༦ རྡ་ས་བོད་མི་མཉམ་ལས་བཟོ་གྲྭ། , 4|46 ,"Dharamshala Tibetan 
Handicraft Production Cum Sales Co-operative industrial society ltd",Active, Head Office ,,,
 ༤།༤༧ ཌལ་ཧོར་ཕུན་ཚོགས་གླིང་བཟོ་གྲྭ། , 4|47 ,Dalhousie Tibetan Refugee Handicraft Center (Phuntsokling),Active, Head Office ,,,
 ༤།༨༢ དབུས་སྣེ་ལེན་འབྲེལ་མཐུད་ཁང་། , 4|82 ,Reception Center(Head Office),Active, Head Office ,,,
 ༤།༨༦ སྤྱི་དཔར་སྡེ་ཚན། , 4|86 ,Chi-Par Section,Active, Head Office ,,,
 ༤།༨༨ དཔལ་འབྱོར་ལས་ཁུངས་ཀྱི་ཡིད་ཆེས་དགེ་རྩ། , 4|88 ,Department of Finance,Active, Head Office ,,,
 ༤།༨༩ རྡ་སྟེང་རྡོ་བཞུན་རླངས་ཛས་ལས་ཁང་། , 4|89 ,TAWS Gas,Active, Head Office ,,,
 ༤།༡༠༡ བཀའ་དྲུང་ཡིག་ཚང་། , 4|101 ,Kashag Secretariat,Active, Head Office ,,,
 ༤།༡༠༢ འཆར་འགོད་ལྷན་ཁང་། , 4|102 ,Planning Commision,Active, Head Office ,,,
 ༤།༡༠༤ གཞུང་ཞབས་འདེམས་བསྐོ་ལྷན་ཁང་། , 4|104 ,Public Service Commission,Active, Head Office ,,,
 ༤།༡༠༥ དཔལ་འབྱོར་ལས་ཁུངས་ཀྱི་བོད་མི་བདེ་དོན་ལས་ཁང་།  , 4|105 ,Department of Finance TAWS,Active, Head Office ,,,
 ༤།༡༠༦ བདེ་སྲུང་ལས་ཁུངས། , 4|106 ,Department of Security,Active, Head Office ,,,
 ༤།༡༠༦(ཀ) ཉམས་ཞིབ། , 4|106 ,Tibet Policy Institute,Active, Head Office ,,,
 ༤།༡༡༡ བོད་གཞུང་ཟློས་གར། , 4|111 ,Tibetan Institute of Performing Arts (TIPA),Active, Head Office ,,,
 ༤།༡༢༢ ཚོགས་དྲུང་ལས་ཁུངས། , 4|122 ,Parliamentary Secretariat,Active, Head Office ,,,
 ༤།༡༢༤ རྡ་ས་ས་གནས་འགོ་འཛིན་ལས་ཁང་། , 4|124 ,Dhasa Tibetan Settlement Office,Active, Head Office ,,,
 ༤།༡༤༡ ཆེས་མཐོའི་ཁྲིམས་ཞིབ་ཁང་། , 4|141 ,Tibetan Supreme Justice Commission,Active, Head Office ,,,
 ༤།༡༤༣ འོས་བསྡུ་ལས་ཁང་། , 4|143 ,Election Commission,Active, Head Office ,,,
 ༤།༡༤༤ དཔལ་འབྱོར་སྤྱི་ཚོགས་ཡར་རྒྱས་ཐེབས་རྩ། , 4|144 ,Department of Finance SARD,Active, Head Office ,,,
 ༤།༡༤༦ གངས་སྐྱིད་ལས་བྱེད་གསོལ་ཚང་། , 4|146 ,Gangkyi Staff Mess,Active, Head Office ,,,
 ༤།༡༤༧ རྡ་ས་རང་བཙན་ཚོགས་ཆུང་། , 4|147 ,Dhasa BRDL,Active, Head Office ,,,
 ༤།༡༥༠ གོ་པལ་པུར་བོད་ཁྱིམ། , 4|150 ,Gopalpur TCV,Active, Head Office ,,,
 ༤།༡༥༡ ནོར་གླིང་རིག་གཞུང་གཅེས་སྐྱོང་དང་ཆོས་ནོར། , 4|151 ,Norbulingka Institute of Tibetan Culture,Active, Head Office ,,,
, 4|151 A ,Choenor ,Active, Head Office ,,,
 ༤།༡༥༣ འགྲོ་བ་མིའི་ཐོབ་ཐང་དང་མང་གཙོ་འཕེལ་རྒྱས་ཁང་། , 4|153 ,Tibetan Centre for Human Rights and Democracy,Active, Head Office ,,,
 ༤།༡༦༤ རྡ་སྟེང་བོད་ཕྲུག་ཁྱིམ་སྡེ། (Village) , 4|164 ,Upper TCV School,Active, Head Office ,,,
 ༤།༡༦༥ བོད་ཁྱིམ་ཤེས་ཡོན་་དང་དགེ་འོས་སློབ་གཉེར་ཁང་། TTC & EDRC  , 4|165 ,TCV  TTC & EDRC,Active, Head Office ,,,
 ༤།༡༨༣ གངས་སྐྱིད་སམ་བྷོ་ཊ་སློབ་གྲྭ། , 4|183 ,Gnagkyi STS School,Active, Head Office ,,,
 ༤།༡༩༨ མེ་དབོན་དཔེ་སྟོན་སློབ་གྲྭ། , 4|198 ,Sambhota Mewoen Tsuglag Petoen School,Active, Head Office ,,,
 ༤།༢༠༡ ཐེག་ཆེན་ཆོས་གླིང་། , 4|201 ,Thekchen Choeling,Active, Head Office ,,,
 ༤།༢༠༣ སྐུ་སྒེར་ཡིག་ཚང་། , 4|203 ,His Holiness Private Office,Active, Head Office ,,,
 ༤།༢༠༨ རྡ་ས་བོད་ཁྱིམ་སྤྱི་ཁྱབ་ལས་ཁང་དང་ཟུར་དངུལ། , 4|208 ,TCV Head Office and Sur-Nyul,Active, Head Office ,,,
 ༤།༢༡༠ རྡ་སྟེང་བོད་ཕྲུག་ཁྱིམ་སྡེ་ཟུང་དངུལ། , 4|210 ,Upper TCV Sur-Nyul,Active, Head Office ,,,
 ༤།༢༣༣ ཌལ་ཧོར་ས་འགོ་ལས་ཁང་། , 4|233 ,Dalhousie Tibetan Settlement Office,Active, Head Office ,,,
 ༤།༢༤༦ ཤེས་རབ་དགའ་ཚལ་སློབ་གླིང་། , 4|246 ,Sherab Ga-tsel-Ling School,Active, Head Office ,,,
 ༤།༢༤༧ སམ་བྷོ་ཌ་བོད་སློབ་ཚོགས་མི་སྤྱི་ཁྱབ་ཡིག་ཚང་། , 4|247 ,STSS Member Head Office,Active, Head Office ,,,
 ༤།༢༤༤ བདེ་དོན་ལྷན་ཚོགས་དང་ཡིད་ཆེས་དགེ་རྩ་ལས་བྱེད་གསོག་དངུལ། , 4|244 ,TAWS and Trust's Staff Provident Fund,Active, Head Office ,,,
 ༤།༢༥༡ བོད་ཁྱིམ་ལས་བྱེད་ཀྱི་གཟིགས་གསོལདང་རྒས་ཕོགས། , 4|251 ,TCV Staff Gratuity Fund Trust & Pension Fund,Active, Head Office ,,,
 ༤།༢༥༧ དཔལ་འབྱོར་འདུ་འགོད། , 4|257 ,Paljor Dugoe (Revenue generation),Inactive, Head Office ,,,
 ༤།༢༦༢ བོད་ཀྱི་གསོ་རིགས་ཆེས་མཐོའི་སྨན་པའི་ལྷན་ཚོགས། , 4|262 ,Central Council of Tibetan Medicine (CCTM),Active, Head Office ,,,
 ༤།༢༩༤ ཊལ་ཧོར་རང་ཚོགས། , 4|294 ,Dalhousie BRDL,Active, Head Office ,,,
 ༤།༣༠༩ དུས་འཁོར་དབང་ཆེན་ཚོགས་ཆུང་། , 4|309 ,Kalachakra Committee,Inactive, Head Office ,,,
 ༤།༣༡༨ དྭང་སློབ་དབུས་ས་གནས་རང་ཚོགས། , 4|318 ,SFF BRDL,Active, Head Office ,,,
 ༤།༣༤༤ གངས་ལྗོངས་དཔལ་འབྱོར་ཞབས་ཞུ་ཁང་། , 4|344 ,Gang-Jong Development Finance Private Ltd,Active, Head Office ,,,
 ༤།༣༥༠ བོད་རྒྱལ་ཡོངས་རྩེད་རིགས་ཚོགས་པ། , 4|350 ,Tibetan National Sports Association,Active, Head Office ,,,
༤།༥ མ་ན་ལི་སམ་བྷོ་ཊ་སློབ་གྲྭ།,4|5,Manali STS School,Active, Head Office ,,,
༤།༥༤ ཀུ་ལུ་ས་འགོ་དང་ཕ་རན་སི་རོགས་ཚོགས།,4|54,Kullu Settlement Office,Active, Head Office ,,,
༤།༢༢༦ སིམ་ལ་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|226,Shimla Tibetan Settlement Office,Active, Head Office ,,,
༤།༥༦ སིམ་ལ་བཟོ་གྲྭ,4|56,Shimla Tibetan Refugee Self Help Handicraft Society,Active, Head Office ,,,
༤།༡༨༢ བུན་ཊར་སམ་བྷོ་ཊ་སློབ་གྲྭ།,4|182,Bhuntar STS School,Inactive, Head Office ,,,
༤།༡༩༤ པ་་ཀུལ་ལྷ་འབྲི་དང་འཚེམས་པོ་སློབ་གཉེར་ཁང་།,4|194,Patlikul Lhadri and Talior Traning School,Inactive, Head Office ,,,
༤།༢༢༧ སྤོན་ཊོ་བཀྲིས་གླིང་ས་འགོ་ལས་ཁང་།,4|227,"Mandi Settlement Office 
(Pandoh Tashi-Ling, Tso Pema, Sundernagar and Mandi)",Active, Head Office ,,,
༤།༢༣༠ སིམ་ལ་རང་ཚོགས།,4|230,Shimla BRDL,Active, Head Office ,,,
༤།༡༡༢ སྤོན་ཊོ་བཀྲིས་གླིང་བཟོ་གྲྭ,4|112,Pandoh Tashiling Tibetan Handicraft Training and Charitable Society,Active, Head Office ,,,
༤།༢۳༨ སིམ་ལ་སྨན་ཁང་།,4|238,Shimla Primary Health Center,Active, Head Office ,,,
༤།༣༥༥ སིམ་ལ་་སྃ་བྷོ་ཊ་སློབ་གྲྭ།,4|355,Shimla CTSA (Unit of Sambhota Tibetan Schools Society),Active, Head Office ,,,
༤།༢༣༩ པོན་ཊོ་དང་མཚོ་པདྨ་སྨན་ཁང་།,4|239,Pandoh Tashiling Primary Health Center,Active, Head Office ,,,
༤།༢༤༩ བོན་གཞིས་ས་འགོ,4|249,Bon Tibetan Settlement Office,Active, Head Office ,,,
༤།༢༤༩ཀ བོན་གཞིས་འཕྲོད་བསྟེན་སྨན་ཁང་།,4|249A,Bon Primary Health Care Centre,Active, Head Office ,,,
༤།༢༦༣ བྷུན་ཊར་དགེ་འོས་མཐོ་སློབ་ཁང་།,4|263,Bhuntar Teachers Training College,Active, Head Office ,,,
༤།༢༦༤ མན་ཊི་སུན་རྡ་ན་གར་རང་ཚོགས།,4|264,Sundernagar BRDL,Active, Head Office ,,,
༤།༢༦༥ བོན་གཞིས་ཊོ་ལན་ཇི་རང་ཚོགས།,4|265,Dolanji BRDL,Active, Head Office ,,,
༤།༢༩༣ ཀུ་ལུ་རང་ཚོགས།,4|293,Kullu BRDL,Active, Head Office ,,,
༤།༢༩༧ མན་ཊི་དང་མཚོ་པདྨ་རང་ཚོགས།,4|297,Mandi & Tso-Pema BRDL,Active, Head Office ,,,
༤།༢༩༩ སྤོན་ཊོ་བཀྲ་ཤིས་གླིང་རང་ཚོགས།,4|299,Pandoh BRDL,Active, Head Office ,,,
༤།༣༢༦ ཌོ་ལན་ཇི་བོན་གཞིས་སྃ་བྷོ་ཊ་སློབ་གྲྭ།,4|326,Dolanji Sambhota Tibetan School,Active, Head Office ,,,
༤།༡༤ འབིར་སུ་ཇ་བོད་ཁྱིམ་སློབ་གྲྭ།,4|14,Bir Suja TCV School,Active, Head Office ,,,
༤།༤༩ ཅོན་ཏ་ར་ནང་ཆེན་བཟོ་གྲྭ།,4|49,Chauntra Nangchen Division Tibetan Khampa industrial Society,Active, Head Office ,,,
༤།༥༠ སྦིར་སྡེ་དགེ་བཟོ་གྲྭ།,4|50,Bir Dege Division Tibetan Khampa industrial Society,Inactive, Head Office ,,,
༤།༥༡ སྦིར་བོད་ཚོགས་བཟོ་གྲྭ།,4|51,Bir Tibetan Society,Active, Head Office ,,,
༤།༨༧ སྦིར་གཞིས་ཁག་གསུམ་གྱི་སྨན་ཁང་།,4|87,Bir Primary Health Care Centre of 3 Settlement,Active, Head Office ,,,
༤།༡༧༤ ཅོན་ཏ་ར་བོད་ཁྱིམ་སློབ་གྲྭ།,4|174,Chauntra TCV School,Active, Head Office ,,,
༤།༡༨༡ ཅོན་ཏ་ར་སམ་བྷོ་ཊ་སློབ་གྲྭ།,4|181,Chauntra STS School,Active, Head Office ,,,
༤།༡༨༨ སྦིར་སམ་བྷོ་ཊ་སློབ་གྲྭ།,4|188,Bir Suja STS School,Inactive, Head Office ,,,
༤།༢༢༡ ཅོན་ཏ་ར་ས་འགོ་ལས་ཁང་།,4|221,Chauntra Tibetan Settlement Office,Active, Head Office ,,,
༤།༢༢༨ སྦིར་སྡེ་དགེ་ས་འགོ་ལས་ཁང་།,4|228,Bir Dege Tibetan Settlement Office,Active, Head Office ,,,
༤།༢༣༢ སྦིར་བོད་ཚོགས་ས་འགོ་ལས་ཁང་།,4|232,Bir Tibetan Society Settlement Office,Active, Head Office ,,,
༤།༢༨༡ སྦིར་བོད་ཚོགས་རང་ཚོགས།,4|281,Bir Tibetan Society BRDL,Active, Head Office ,,,
༤།༢༩༦ ཅོན་ཏ་ར་རང་ཚོ༣༣༠༡,4|296,Chauntra BRDL,Active, Head Office ,,,
༤།༣༠༠ ཅོན་ཏ་ར་གསོ་རིག་྄སྨན་དཔྱད་ཉམས་ཞིབ་ཁང་།,4|300,Chauntra Sowa-Rigpa Study & Research (CSRSR) (Unit of TMAI),Active, Head Office ,,,
༤།༣༠༡ སྦིར་སྡེ་དགེ་རང་ཚོགས།,4|301,Bir Dege BRDL,Active, Head Office ,,,
༤།༣༥༦ བཀྲ་ཤེས་ལྗོངས་རང་ཚོགས།,4|356,Tashi Jong BRDL,Active, Head Office ,,,
༤།༩ སུད་སི་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,4|9,Office of Tibet - Swiss,Active, Head Office ,,,
༤།༡༠ ཨ་རི་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,4|10,Office of Tibet - US,Active, Head Office ,,,
༤།༣༩ དབྱིན་ལེན་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,4|39,Office of Tibet - London (UK),Active, Head Office ,,,
༤།༤༢ ཉི་ཧོང་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,4|42,Office of Tibet - Japan,Active, Head Office ,,,
༤།༩༡ ཕ་རན་སི་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,4|91,Office of Tibet - France,Active, Head Office ,,,
༤།༩༣ ལྷོ་ཨ་ཕི་རི་ཀ་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,4|93,Office of Tibet - Pretoria (South Africa),Active, Head Office ,,,
༤།༩༤ ཐེ་ཝན་སྐུ་ཚབ་དོན་གཅོད་ཁང་གི་བོད་ཀྱི་ཐེབས་རྩ་ལས་ཁང་།,4|94,Office of Tibet - Taiwan,Active, Head Office ,,,
༤།༩༥ ཨོ་སི་ཀྲེ་ལི་ཡ་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,4|95,Office of Tibet - Australia,Active, Head Office ,,,
༤།༢༣༧ རུ་སོག་དོན་ཁང་།,4|237,Office of Tibet - Russia,Active, Head Office ,,,
༤།༣༢༤ ལྷོ་ཨ་མི་རི་ཀ་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,4|324,Office of Tibet - South America,Active, Head Office ,,,
༤།༣༦ ལྡི་ལི་ས་གནས་འགོ་འཛིན་ལས་ཁང།,4|36,Delhi Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༣༨ ལྡི་ལི་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,4|38,Tibet Bureau Delhi,Inactive, Dekyiling Branch ,,,
༤།༡༢༨ ལྡི་ལི་སྣེ་ལེན་ཁང་ཡན་ལག,4|128,Delhi Reception Centre Branch,Inactive, Dekyiling Branch ,,,
༤།༡༣༠ ལྡི་ལི་བོད་ཁྱིམ་སྡོད་ཤག,4|130,Delhi TCV Youth Hostel,Inactive, Dekyiling Branch ,,,
༤།༡༩༥ སྤྱི་མཐུན་མཉམ་འབྲེལ།,4|195,Federation of Tibetan Cooperatives in India Head Quarter ,Inactive, Dekyiling Branch ,,,
༤།༡༩༩ སྤྱི་མཐུན་མཉམ་འབྲེལ་གྱི་ལྡི་ལི་ཕྱི་ཚོང་ཁང་།,4|199,"Federation of Tibetan Cooperatives in India, Delhi",Inactive, Dekyiling Branch ,,,
༤།༢༠༥ ལྡི་ལི་ས་གནས་རང་ཚོགས།,4|205,Delhi BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༢༩ ལྡི་ལི་སམ་ཡས་གླིང་སྨན་ཁང་།,4|229,Delhi Samyeling Primary Health Center,Inactive, Dekyiling Branch ,,,
༤།༢༥༠ ལྡི་ལི་བོད་ཁང་།,4|250,Tibet House - Delhi,Inactive, Dekyiling Branch ,,,
༤།༣༥༤ སྨན་རྩིས་ཁང་གི་་ལྡི་ལི་ཕྱི་ཚོང་ཁང་།,4|354,Delhi Men-Tse-Khang Exports,Inactive, Dekyiling Branch ,,,
༤།༦ བལ་ཡུལ་སྲོང་བཙན་སློབ་གྲྭ།,4|6,Nepal Songtsen Bhrikuti Boarding High School,Inactive, Nepal Branch ,,,
༤།༧ བལ་ཡུལ་འཕགས་ཤིང་རྣམ་རྒྱལ་འབྲིང་སློབ།,4|7,Nepal Swoyambhu Namgyal Middle Boarding School,Inactive, Nepal Branch ,,,
༤།༨ བལ་ཡུལ་གོར་ཁ་ན་རྣམ་རྒྱལ་མཐོ་སློབ།,4|8,Nepal Gokarna Namgyal Higher Secondary School,Inactive, Nepal Branch ,,,
༤།༦༢ བལ་ཡུལ་ཤར་ཁུམ་མཉམ་འབྲེལ།,4|62,Nepal Sharkhum Delek-ling Handicraft Centre,Inactive, Nepal Branch ,,,
༤།༦༦ བལ་ཡུལ་འཇོ་འཁེལ་བཟོ་གྲྭ།,4|66,Nepal Jawalakhel Handicraft Centre,Inactive, Nepal Branch ,,,
༤།༦༨ འཇོ་འཁེལ་མཉམ་འབྲེལ།,4|68,Jawalakhel Bahumukhi Co-operative Society Ltd,Inactive, Nepal Branch ,,,
༤།༩༦ བལ་ཡུལ་སི་ཀྲི་སི་གདན་ཚོང་ཁང་།,4|96,Nepal CTC Carpets,Inactive, Nepal Branch ,,,
༤།༩༧ བལ་ཡུལ་དགའ་ལྡན་རུམ་གདན་ཕྱི་ཚོང་ཁང་།,4|97,Nepal Gaden Carpets,Inactive, Nepal Branch ,,,
༤།༡༡༣ སྤོག་ར་བཀྲིས་དཔལ་འཁྱིལ་བཟོ་གཞིས་ལས་ཁང་།,4|113,Nepal Pokhara Tashi Palkhiel Handicraft Centre,Inactive, Nepal Branch ,,,
༤།༡༡༥ བལ་ཡུལ་དོན་་ཁང་དང་བལ་ཡུལ་སྣེ་ལེན་ཡན་ལག,4|115,Nepal Reception Centre Branch,Inactive, Nepal Branch ,,,
༤།༡༡༧ བལ་ཡུལ་འཇོ་འཁེལ་ཨ་ཏི་ཤ་ཉིན་སློབ།,4|117,Nepal Jawalakhel Atisha Primary School,Inactive, Nepal Branch ,,,
༤།༡༡༩ སྤོག་ར་བཀྲིས་གླིང་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|119,Nepal Pokhara Tashiling Settlement Office,Inactive, Nepal Branch ,,,
༤།༡༢༦ བལ་ཡུལ་འཇོ་འཁེལ་གངས་ཅན་བདེ་རྩ།,4|126,Nepal Snow-Lion Foundation,Inactive, Nepal Branch ,,,
༤།༡༣༣ སྤོག་ར་གློ་སྒྲིག་བདེ་དོན་ཚོགས་པ། ཨ་ན་སྤུར་ན་གསོལ་མགྲོན་ཁང་།,4|133,"Nepal Pokhara Lodrik Society, Annapurna Guest House",Inactive, Nepal Branch ,,,
༤།༡༥༥ སྤོག་ར་བཀྲིས་དཔལ་འཁྱིལ་མཉམ་འབྲེལ།,4|155,Pokhara Tashi Palkhiel Tibetan Co-operative Society Ltd,Inactive, Nepal Branch ,,,
༤།༡༥༦ སྤོག་ར་བཀྲིས་གླིང་བཟོ་གཞིས་ལས་ཁང་། ས་འགོ་ལས་ཁང་།,4|156,Nepal Pokhara Tashiling Settlement Office,Inactive, Nepal Branch ,,,
༤།༡༧༩ བལ་ཡུལ་ཚེ་རིང་རྒས་གསོ་ཁང་།,4|179,Nepal Tsering Elder's Home,Inactive, Nepal Branch ,,,
༤།༡༨༥ སྤོག་ར་དཔལ་འབྱོར་གླིང་འཕྲོད་བསྟེན་སྨན་ཁང་།,4|185,Nepal Paljorling Primary Health Center,Inactive, Nepal Branch ,,,
༤།༡༨༦ སྤོག་ར་བྱམས་པ་གླིང་འཕྲོད་བསྟེན་སྨན་ཁང་།,4|186,Nepal Jampaling Primary Health Center,Inactive, Nepal Branch ,,,
༤།༢༠༧ བལ་ཡུལ་རྒྱས་ས་དང་འཕགས་ཤིང་ས་འགོ་ལས་ཁང་།,4|207,Nepal Kathmandu & Phakshing Settlement Office,Inactive, Nepal Branch ,,,
༤།༢༠༩ བལ་ཡུལ་མཆོད་འཇོར་ས་འགོ་ལས་ཁང་།,4|209,Nepal Choejor Settlement Office,Inactive, Nepal Branch ,,,
༤།༢༡༦ གློ་སྒྲིག་བྱམས་གླིང་དང་། དཔལ་གླིང་། བཀྲིས་སྒང་ས་འགོ་ལས་ཁང་།,4|216,"Nepal Lodrik Jampaling, Paljorling and Tashigang Settlement Office",Inactive, Nepal Branch ,,,
༤།༢༡༨ བལ་ཡུལ་ཀེ་ལཤ་སྨན་རྩིས་ཚོགས་པ།,4|218,Nepal Mentse Khang,Inactive, Nepal Branch ,,,
༤།༦༡ བལ་ཡུལ་ཤར་ཁུམ་ས་འགོ,4|61,Nepal Sharkhum Tibetan Settlement Office,Inactive, Nepal Branch ,,,
༤།༢༧༠ ཇོར་པ་ཀྲི་རང་ཚོགས།,4|270,Nepal Jorpati BRDL,Inactive, Nepal Branch ,,,
༤།༢༧༡ བལ་ཡུལ་མཆོད་རྟེན་རང་ཚོགས།,4|271,Nepal Boudha BRDL,Inactive, Nepal Branch ,,,
༤།༢༧༢ བལ་ཡུལ་རྒྱལ་ས་རང་ཚོགས།,4|272,Nepal Kathmandu BRDL,Inactive, Nepal Branch ,,,
༤།༢༧༣ བལ་ཡུལ་འཕགས་ཤིང་རང་ཚོགས།,4|273,Nepal Pharshing BRDL,Inactive, Nepal Branch ,,,
༤།༢༨༠ བལ་ཡུལ་འཇོ་འཁེལ་རང་ཚོགས།,4|280,Nepal Jawalakhel BRDL,Inactive, Nepal Branch ,,,
༤།༢༨༤ སྤོག་ར་བཀྲ་ཤིས་གླིང་རང་ཚོགས།,4|284,Nepal Pokhara Tashiling BRDL,Inactive, Nepal Branch ,,,
༤།༢༨༥ སྤོག་ར་བཀྲིས་དཔལ་འཁྱིལ་རང་ཚོགས།,4|285,Nepal Pokhara Palkhiel BRDL,Inactive, Nepal Branch ,,,
༤།༢༨༦ སྤོག་ར་དཔལ་འབྱོར་གླིང་རང་ཚོགས།,4|286,Nepal Pokhara Paljorling BRDL,Inactive, Nepal Branch ,,,
༤།༢༨༧ སྤོག་ར་བྱམས་པ་གླིང་རང་ཚོགས།,4|287,Nepal Pokhara Jampaling BRDL,Inactive, Nepal Branch ,,,
༤།༣༡༤ བལ་ཡུལ་ནོར་འཛིན་གླིང་རང་ཚོགས།,4|314,Nepal Norzinling BRDL,Inactive, Nepal Branch ,,,
༤།༣༣༨ ཤར་ཁུམ་བདེ་ལེགས་གླིང་ས་གནས་རང་ཚོགས།,4|338,Nepal Sharkhum Delekling BRDL,Inactive, Nepal Branch ,,,
༤།༣༣༩ ཤར་ཁུམ་ནགས་ཆེ་ས་གནས་རང་ཚོགས།,4|339,Nepal Sharkhum Nagche BRDL,Inactive, Nepal Branch ,,,
༤།༣༤༡ ཝ་ལུང་བསམ་འཕེལ་གླིང་ས་གནས་རང་ཚོགས།,4|341,Nepal Walung Sampheling BRDL,Inactive, Nepal Branch ,,,
༤།༣༤༥ བལ་ཡུལ་མ་ནང་ས་གནས་རང་ཚོགས།,4|345,Nepal Manang BRDL,Inactive, Nepal Branch ,,,
༤།༣༤༩ ར་སུ་ཝ་དགེ་རྒྱས་གླིང་ས་གནས་རང་ཚོགས།,4|349,Rasuwa Gegyeling BRDL,Inactive, Nepal Branch ,,,
༤།༣༢ མན་སྤར་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|32,Mainpat Tibetan Settlement Office,Inactive, South Branch ,,,
༤།༥༩ མན་སྤར་བོད་མིའི་མཉམ་འབྲེལ།,4|59,Mainpat Tibetan Refugee Multipurpose Co-operative Society Ltd,Inactive, South Branch ,,,
༤།༦༠ ཨོ་རི་ས་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|60,Orisa Settlement Office,Inactive, South Branch ,,,
༤།༦༩ ཨོ་རི་ས་ཕུན་ཚོགས་གླིང་བོད་མིའི་མཉམ་འབྲེལ།,4|69,Odisha Phuntsokling Multi-Purppose Tibetan Co-operative Society Ltd,Inactive, South Branch ,,,
༤།༧༠ ཨོ་རི་ས་ཕུན་གླིང་བོད་མི་རུམ་བཟོ་མཉམ་འབྲེལ།,4|70,Odisha Phuntsokling Tibetan Handicraft Centre,Inactive, South Branch ,,,
༤།༧༧ སྦན་རྡ་་ར་ས་འགོ་དང་སྤྱི་མི་ལས་ཁང་།,4|77,Bandra Tibetan Settlement Office & Chimi Office,Inactive, South Branch ,,,
༤།༧༨ སྦན་རྡ་ར་ནོར་རྒྱས་གླིང་བོད་མིའི་མཉམ་འབྲེལ།,4|78,Bhandara Norgyeling Tibetan Multi-Purpose Co-operative Society Ltd,Inactive, South Branch ,,,
༤།༩༩ ཨོ་རི་ས་ཕུན་ཚོགས་གླིང་སྨན་ཁང་།,4|99,Odisha Primary Health Center,Inactive, South Branch ,,,
༡།༡༣༢ ཨོ་རིས་ཕུན་ཚོགས་གླིང་ས་གནས་གྲོས་ཚོགས།,1|132,Odisha Phuntsokling LTA,Inactive, South Branch ,,,
༤།༡༧༨ སྦན་རྡ་ར་འཕྲོད་བསྟེན་སྨན་ཁང་།,4|178,Bhandara Primary Health Center,Inactive, South Branch ,,,
༤།༢༡༧ མན་སྤར་ཕན་བདེ་གླིང་འཕྲོད་བསྟེན་སྨན་ཁང་།,4|217,Mainpat Phendeyling Primary Health Center,Inactive, South Branch ,,,
།༤།༣༠༤ སྦན་རྡ་ར་རང་ཚོགས།,|4|304,Bhandara BRDL,Inactive, South Branch ,,,
༤།༣༠༥ སྦན་རྡ་ར་སམ་བྷོ་ཊ་སློབ་གྲྭ,4|305,Bandra STS School,Inactive, South Branch ,,,
༤།༣༠༨ མན་སྤར་སྃ་བྷོ་ཊ་སློབ་གྲྭ,4|308,Mainpat STS School,Inactive, South Branch ,,,
༤།༣༡༣ མན་སྤར་ས་གནས་རང་ཚོགས།,4|313,Mainpat BRDL,Inactive, South Branch ,,,
༤།༣༤༦ བློ་བྷར་སིང་ས྄་བྷོ་ཊ་གཞི་རིམ་འཔག་མའི་སློབ་གྲྭ།,4|346,Lobersing Primary School,Inactive, South Branch ,,,
༤།༣༤༧ ཅན་དྷ་གྷི་རི་སྃ་བྷོ་ཊ་གཞི་རིམ་འཔག་མའི་སློབ་གྲྭ།,4|347,Chandragiri Primary School,Inactive, South Branch ,,,
༤།༤ སྤོན་ཊ་སམ་བྷོ་ཊ་སློབ་གྲྭ།,4|4,Paonta STS School,Inactive, Dekyiling Branch ,,,
༤།༤༨ སྤོན་ཊ་ཆོལ་གསུམ་བཟོ་གྲྭ་,4|48,Paonta Tibetan Cholsum Industrial Society,Inactive, Dekyiling Branch ,,,
༤།༥༣ ཁམས་ཀཿཐོག་བཟོ་གྲྭ་ ས་ཊོན་བཟོ་གྲྭ་,4|53,Sataun Kham Kathok Tibetan Society,Inactive, Dekyiling Branch ,,,
༤།༥༧ ལྡེ་ལྡུན་ས་འགོ་དང། འཐུང་ཆུའི་ལས་གཞི།,4|57,Dehradun Settlement Office & Drinking Water Project,Inactive, Dekyiling Branch ,,,
༤།༥༨ བདེ་སྐྱིད་གླིང་བོད་མིའི་ལག་ཤེས་བཟོ་གྲྭ།,4|58,Dekyiling Tibetan Handicraft Cum Training & Charitable Society,Inactive, Dekyiling Branch ,,,
༤།༡༥༢ ལྡེ་ལྡུན་བོད་ཁྱིམ་ལས་རིག་སློབ་གཉེར་ཁང་།,4|152,Dehradun TCV Tibetan Private Industrial Training Institute (TCV ITI),Inactive, Dekyiling Branch ,,,
༤།༡༥༤ བདེ་སྐྱིད་གླིང་སྨན་ཁང་།,4|154,Dekyiling Primary Health Center,Inactive, Dekyiling Branch ,,,
༤།༡༦༠ མ་སུ་རི་བོད་ཁྱིམ།,4|160,THF Mussoorie,Inactive, Dekyiling Branch ,,,
༤།༡༦༢ མངོན་དགའ་བོད་ཕྲུག་དབང་པོ་སྐྱོན་ཅན་གྱི་སློབ་གྲྭ,4|162,Ngoenga School for Tibetan Children with Special Needs,Inactive, Dekyiling Branch ,,,
༤།༡༦༨ རཱཇ་སྤུར་བུ་མེད་མཉམ་ལས་བཟོ་གྲྭ།,4|168,Rajpur Tibetan Women's Centre,Inactive, Dekyiling Branch ,,,
༤།༡༧༥ ལྡེ་ལྡུན་བོད་ཁྱིམ་སློབ་གྲྭ།,4|175,Dehradun Selakui TCV School,Inactive, Dekyiling Branch ,,,
༤།༡༩༡ སྤུ་རུ་ཝ་ལ་སམ་བྷོ་ཊ་སློབ་གྲྭ།,4|191,Puruwala STS School,Inactive, Dekyiling Branch ,,,
༤།༡༩༣ བདེ་སྐྱིད་གླིང་སམ་བྷོ་ཊ་སློབ་གྲྭ།,4|193,Dekyiling STS School,Inactive, Dekyiling Branch ,,,
༤།༢༠༦ བདེ་སྐྱིད་གླིང་ས་འཐུས་ལས་ཁང་།,4|206,Dekyiling LTA,Inactive, Dekyiling Branch ,,,
༤།༢༡༡ དོན་གྲུབ་གླིང་ས་གནས་རང་ཚོགས། ,4|211,Dhondupling BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༤༡ མ་སུ་རི་རང་ཚོགས།,4|241,Mussoorie BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༡༢ གླིང་ཚོང་ས་གནས་རང་ཚོགས།,4|212,Lingtsong BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༡༣ བདེ་གླིང་ས་གནས་རང་ཚོགས།,4|213,Dekyiling BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༡༤ སྤོན་ཊ་ཆོལ་གསུམ་ས་གནས་རང་ཚོགས།,4|214,Paonta Cholsum BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༢༠ ར་ཇི་སྤུར་རང་ཚོགས།,4|220,Rajpur BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༢༢ ས་ཊོན་ས་འགོ་ལས་ཁང་།,4|222,Sataun Kathok Tibetan Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༢༢༣ ཧར་སྤུར་ས་འགོ་ལས་ཁང་།,4|223,Herbertpur Doegu Yugyaling Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༢༢༤ སྤུར་རུ་ཝ་ལ་ས་འགོ་ལས་ཁང་།,4|224,Puruwala Sakya Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༢༢༥ སྤོན་ཊ་ཆོལ་གསུམ་ས་འགོ་ལས་ཁང་།,4|225,Paonta Cholsum Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༢༣༤ སྤུ་རུ་ཝ་ལ་རང་ཚོགས།,4|234,Puruwala BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༤༨ ཧ་པ་སྤུར་རང་ཚོགས།,4|248,Herbertpur BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༤༢ སྤུ་རུ་ཝ་ལ་བཟོ་གྲ,4|242,Puruwala BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༥༨ ཀམ་ཀཿཐོག་ འཕྲོད་བསྟེན་སྨན་ཁང་།,4|258,Sataun Kathok Primary Health Center,Inactive, Dekyiling Branch ,,,
༤།༢༧༥ ཀུམ་རའོ་རང་ཚོགས།,4|275,Kumrao BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༧༦ ཀུམ་རའོ་འཕྲོད་བསྟེན་སྨན་ཁང་།,4|276,Kumrao Primary Health Center,Inactive, Dekyiling Branch ,,,
༤།༢༧༧ ཀུམ་རའོ་ས་འགོ་ལས་ཁུངས།,4|277,Kumrao Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༢༨༣ ཀུམ་རའོ་བོད་མི་བདེ་དོན་ཚོགས་པ།,4|283,Kumrao Tibetan Welfare Society,Inactive, Dekyiling Branch ,,,
༤།༣༠༣ ནེ་ནི་ཌལ་རང་ཚོགས།,4|303,Nanital BRDL,Inactive, Dekyiling Branch ,,,
༤།༣༢༠ ས་ཧ་རན་སྤུར་ས་གནས་རང་ཚོགས།,4|320,Saharanpur BRDL,Inactive, Dekyiling Branch ,,,
༤།༣༢༩ ཧ་རི་ད་ཝར་ས་གནས་རང་ཚོགས།,4|329,Haridwar BRDL,Inactive, Dekyiling Branch ,,,
༤།༣༣༤ ས་ལུ་ག་ར་སྤོས་བཟོ་སྡེ་ཚན།,4|334,Salugara Incense Production Unit (A Unit of TMAI),Inactive, Dekyiling Branch ,,,
༤།༣༣༥ འབྲུག་བསྡོད་བོད་མིའི་ལྟ་རྟོག་ལས་ཁུངས།,4|335,Bhutan Tibetan Welfare Office,Inactive, Dekyiling Branch ,,,
༤།༣༣༦ འབྲུག་ས་གནས་རང་ཚོགས།,4|336,Bhutan BRDL,Inactive, Dekyiling Branch ,,,
༤།༣༣༧ ས་ཊོན་ཁམས་ཀ་ཐོག་སྤྱི་བརྒྱ་སྡེ་ཚན།,4|337,Sataun Chigyak Office,Inactive, Dekyiling Branch ,,,
༤།༣༤༠ སྤོན་ཊ་ཆོལ་གསུམ་སྤྱི་བརྒྱ་ཡིག་ཚང་།,4|340,Paonta Cholsum Chigyak Office,Inactive, Dekyiling Branch ,,,
༤།༣༤༣ ཧར་པ་སྤུར་སྤྱི་བརྒྱ་ཡིག་ཚང་།,4|343,Herbertpur Chigyak Office,Inactive, Dekyiling Branch ,,,
༤།༣༤༨ བདེ་གླིང་གསོ་རིག་སྨན་དཔྱད་ཉམས་ཞིབ་བསྟི་གནས་ཁང་།,4|348,Dekyiling Sowarigpa,Inactive, Dekyiling Branch ,,,
༤།༣༥༣ ཧར་པ་སྤུར་བོད་མིའི་མཉམ་སྦྲེལ།,4|353,Herbertpur Tibetan Joint Co-operative Agriculture Society Ltd,Inactive, Dekyiling Branch ,,,
༤།༣༦༡ མ་སུ་རི་་སཾ་བྷོ་ཊ་སློབ་གྲྭ།,4|361,Mussoorie Sambhota Tibetan School,Inactive, Dekyiling Branch ,,,
༤།༣༦༢ ཧར་པ་པུར་སཾ་བྷོ་ཊ་སློབ་གྲྭ།,4|362,Herbertpur Sambhota Tibetan School,Inactive, Dekyiling Branch ,,,
༤།༢༧ སྒང་ཏོག་བོད་ཀྱི་གསོལ་མགྲོན་ཁང་།,4|27,Gangtok Hotel Tibet,Inactive, Dekyiling Branch ,,,
༤།༦༣ འབུམ་ལ་བསྟན་སྒང་མཉམ་འབྲེལ།,4|63,Tenzin Gang Multipurpose Cooperative Society Ltd,Inactive, Dekyiling Branch ,,,
༤།༦༤ ཏི་ཛུ་དར་རྒྱས་གླིང་མཉམ་འབྲེལ།,4|64,Tezu Dhargayling Tibetan Multipurpose Co-operative Society Ltd,Inactive, Dekyiling Branch ,,,
༤།༦༥ མེའོ་ཆོས་འཕེལ་གླིང་མཉམ་འབྲེལ།,4|65,Miao Choephelling Tibetan Service Co-operative Society Ltd,Inactive, Dekyiling Branch ,,,
༤།༡༠༣ འབུམ་ལ་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|103,Bomdila Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༡༠༩ བསྟན་འཛིན་སྒང་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|109,Tenzingang Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༡༡༤ སྒང་ཏོག་ས་གནས་འགོ་འཛིན་ལས་ཁང་དང་སྨན་ཁང་།,4|114,Gangtok Settlement Office & PHC,Inactive, Dekyiling Branch ,,,
༤།༡༢༧ བསུ་ན་མདའ་མཉམ་འབྲེལ།,4|127,Sonada Co-operative Society & School's Hostel,Inactive, Dekyiling Branch ,,,
༤།༡༤༨ ཏེ་ཛུ་དར་རྒྱས་གླིང་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|148,Tezu Dhargye Ling Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༡༤༩ མེའོ་ཆོས་འཕེལ་གླིང་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|149,Miao Choephelling Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༡༥༨ སྒང་ཏོག་སམ་བྷོ་ཊ་་སློབ་གྲྭ།,4|158,Gangtok STS ,Inactive, Dekyiling Branch ,,,
༤།༣༥༢ ལྡི་མ་སྤུར་ས་གནས་རང་ཚོགས།,4|352,Dimapur BRDL,Inactive, Dekyiling Branch ,,,
༤།༣༥༧ སྒང་ཏོག་འཕྲོད་བསྟེན་སྨན་ཁང་།,4|357,Gangtok Primary Health Center,Inactive, Dekyiling Branch ,,,
༤།༣༥༨ རྡོ་རྗེ་གླིང་སམ་བྷོ་ཊ།,4|358,Darjeeling Sambhota Tibetan School,Inactive, Dekyiling Branch ,,,
༤།༣༥༩ ཀ་སྦུག་སམ་བྷོ་ཊ།,4|359,Kalimpong Sambhota Tibetan School,Inactive, Dekyiling Branch ,,,
༤།༡༧༣ ར་ཝང་ལ་ས་འགོ་་དང་ཕ་རན་སི་རོགས་ཚོགས།,4|173,Ravangla Kunphenling Settlement Office & AET,Inactive, Dekyiling Branch ,,,
༤།༡༧༦ ར་ཝང་ལ་ཀུན་འཕན་གླིང་མཉམ་འབྲེལ།,4|176,Ravangla Kunphenling Tibetan Co-operative Society Ltd,Inactive, Dekyiling Branch ,,,
༤།༡༨༩ ཤི་ལོང་སམ་བྷོ་ཊ་སློབ་གྲྭ།,4|189,Shillong STS School,Inactive, Dekyiling Branch ,,,
༤།༡༩༠ སྤོག་རི་ཡ་བོང་སམ་བྷོ་ཊ་སློབ་གྲྭ།,4|190,Pokhriabong STS School,Inactive, Dekyiling Branch ,,,
༤།༢༠༢ ཤི་ལོང་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|202,Shillong Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༢༡༥ རྡོར་གླིང་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|215,Darjeeling Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༢༣༡ སུ་ན་མདའ་ས་འགོ་དང་སྨན་ཁང་།,4|231,Sonada Tibetan settlement office and Primary Health Care,Inactive, Dekyiling Branch ,,,
༤།༢༣༥ རང་ཝང་ལ་སྨན་ཁང་།,4|235,Ravangla Primary Health Center,Inactive, Dekyiling Branch ,,,
༤།༢༣༦ ཀ་སྦུག་ས་འགོ་ལས་ཁང་།,4|236,Kalimpong Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༢༥༥ སི་ལོང་རང་ཚོགས།,4|255,Shillong BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༥༩ བསྟན་སྒང་འཕྲོད་བསྟེན་སྨན་ཁང་།,4|259,Tenzingang Primary Health Center,Inactive, Dekyiling Branch ,,,
༤།༢༦༠ མེའོ་རང་ཚོགས།,4|260,Miao BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༦༡ རྡོར་གླིང་རང་ཚོགས།,4|261,Darjeeling BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༦༦ ཀ་སྤུག་རང་ཚོགས།,4|266,Kalimpong BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༦༧ ས་ལུ་སྒ་ར་རང་ཚོགས།,4|267,Salugara BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༩༠ ཀྲུ་ཀྲིང་རང་ཚོགས།,4|290,Tuting BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༩༡ ཀྲུ་ཀྲིང་ས་འགོ་དང་སྨན་ཁང་།,4|291,Tuting Tibetan Settlement Office & Primary Health Center,Inactive, Dekyiling Branch ,,,
༤།༢༤༠ བསུ་ན་མདའ་ས་འགོ་ལས་ཁང་།,4|240,Sonada Tibetan Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༢༤༥ སྒང་ཏོག་རང་བདེན་ཚོགས་ཆུང་།,4|245,Gangtok BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༥༢ ཏེ་ཛུ་རང་ཚོགས།,4|252,Tezu BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༥༣ ར་ཝང་ལ་རང་ཚོགས།,4|253,Ravangla BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༥༤ བསོ་ན་མདའ་རང་ཚོགས།,4|254,Sonada BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༥༦ བསྟན་སྒང་རང་ཚོགས།,4|256,Tenzingang BRDL,Inactive, Dekyiling Branch ,,,
༤།༣༠༢ འབུམ་སྡེ་ལ་རང་ཚོགས།,4|302,Bomdila BRDL,Inactive, Dekyiling Branch ,,,
༤།༣༠༦ བསྟན་སྒང་སམ་བྷོ་ཊ་སློབ་གྲ,4|306,Tenzingang STS School,Inactive, Dekyiling Branch ,,,
༤།༣༡༠ ཨོ་ལ་ཝ་རི་རང་ཚོགས།་ཀ་སྤུག,4|310,Olabari BRDL,Inactive, Dekyiling Branch ,,,
༤།༣༡༡ ཛ་ཡི་སྒང་ས་གནས་རང་ཙོགས། ཀ་སྤུག,4|311,Jaigaon BRDL,Inactive, Dekyiling Branch ,,,
༤།༣༡༢ ར་ཝང་ལ་སྃ་བྷོ་ཊ་སློབ་གྲྭ,4|312,Ravangla STS School,Inactive, Dekyiling Branch ,,,
༤།༣༡༥ མེའོ་སྃ་བྷོ་ཊ་སརྦ་གྲྭ,4|315,Miao STS,Inactive, Dekyiling Branch ,,,
༤།༣༡༦ ཏེ་ཛུ་སྃ་བྷོ་ཊ་སློབ་གྲྭ,4|316,Tezu STS School,Inactive, Dekyiling Branch ,,,
༤།༣༢༥ མོན་ཏ་དབང་ས་གནས་རང་ཚོགས།,4|325,Tawang BRDL,Inactive, Dekyiling Branch ,,,
༤།༣༤༢ བསུ་ན་མདའ་སྃ་བྷོ་ཊ་སློབ་གྲྭ།,4|342,Sonada STS School,Inactive, Dekyiling Branch ,,,
༤།༨༡ ལ་དྭགས་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|81,Ladakh Settlement Office,Inactive, Dekyiling Branch ,,,
༤།༡༠༨ ལ་དྭགས་བསོད་ནམས་གླིང་མཉམ་འབྲེལ་དང་བཟོ་གྲོ།,4|108,Ladakh Sonamling Tibetan Refugee Service Co-operative Society Ltd,Inactive, Dekyiling Branch ,,,
༤།༡༢༣ ལ་དྭགས་འཕྲོད་བསྟེན་སྨན་ཁང་།,4|123,Ladakh Primary Health Center,Inactive, Dekyiling Branch ,,,
༤།༡༩༧ ལ་དྭགས་བོད་ཕྲུག་ཁྱིམ་སྡེ།,4|197,Ladakh TCV School,Inactive, Dekyiling Branch ,,,
༤།༢༠༤ ལ་དྭགས་ས་གནས་རང་ཚོགས།,4|204,Ladakh Leh BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༧༨ ལ་དགས་བྱང་ཐང་རང་ཚོགས།,4|278,Ladakh Jangthang BRDL,Inactive, Dekyiling Branch ,,,
༤།༢༧༩ ལ་དགས་སྨན་རྩིས་རིག་གཞུང་ལྟེ་གནས་ཁང་།,4|279,Ladakh Mentse Khang,Inactive, Dekyiling Branch ,,,
༤།༣༣ མོན་གོ་འདོད་རྒུ་གླིང་སྨན་ཁང་།,4|33,Mundgod Duguling Primary Health Center,Inactive, South Branch ,,,
༤།༣༤ ཧོན་སུར་ཕན་བདེ་སྨན་ཁང་།,4|34,Hunsur Tibetan Phende Hospital Association,Inactive, South Branch ,,,
༤།༣༥ ཀོ་གལ་དོན་ལྡན་གླིང་སྨན་ཁང་།,4|35,Kollegal Dondenling Primary Health Center,Inactive, South Branch ,,,
༤།༣༧ སྦེལ་ཀོབ་འཚོ་བྱེད་ཁང་གསར་སྨན་ཁང་།,4|37,Bylakuppe Tso-Jhe Khangsar Charity Hospital Society,Inactive, South Branch ,,,
༤།༧༡ སྦེལ་ཀོབ་ལུགས་བསམ་བོད་མིའི་མཉམ་འབྲེལ།,4|71,Bylakuppe Lugsam Dairy Cooperative,Inactive, South Branch ,,,
༤།༧༢ སྦེལ་ཀོབ་བདེ་སྐྱིད་སླར་གསོ་བོད་མིའི་མཉམ་འབྲེལ།,4|72,Bylakuppe Dickey Larsoe Dairy Cooperative,Inactive, South Branch ,,,
༤།༧༣ ཧོན་སུར་རབ་གླིང་བོད་མིའི་མཉམ་འབྲེལ།,4|73,Hunsur Tibetan Rabgayling Primary Agricultural Credit Co-operative Society Ltd,Inactive, South Branch ,,,
༤།༧༤ ཀོ་གལ་དོན་གླིང་བོད་མིའི་མཉམ་འབྲེལ།,4|74,Kollegal Dhondenling Primary Agricultural Co-operative Society Ltd,Inactive, South Branch ,,,
༤།༨༣ མོན་གོ་འདོད་རྒུ་གླིང་བོད་མིའི་མཉམ་འབྲེལ།,4|83,Mundgod Doeguling Primary Agriculture Co-operative Society Ltd,Inactive, South Branch ,,,
༤།༨༤ མོན་གོ་འདོད་རྒུ་གླིང་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|84,Mundgod Doeguling Settlement Office,Inactive, South Branch ,,,
༤།༨༥ སྦེང་ལོར་ལྷོ་སྤྱི་ལས་ཁང་།,4|85,Bangalore South Zone Chief Representative Office,Inactive, South Branch ,,,
༤།༡༡༨ སྦེལ་ཀོབ་བདེ་སླར་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|118,Bylakuppe Dickey Larsoe Settlement Office,Inactive, South Branch ,,,
༤།༡༢༡ ཧོན་སུར་རབ་རྒྱས་གླིང་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|121,Hunsur Rabgayling Settlement Office,Inactive, South Branch ,,,
༤།༡༦༡ ནང་སྲེད་སྦེང་ལོར་ལས་རིགས་སྦྱོང་བརྡར་ཁང་།,4|161,Bengaluru Institute For Small Trade Learning (Nelamangala),Inactive, South Branch ,,,
༤།༡༦༦ སྦེལ་ཀོབ་སྐྱེ་ལྡན་སོ་ནམ་ཉམས་ཞིབ་སྦྱོང་བརྡར་ཁང་།,4|166,Bylakuppe Organic Research & Training Center,Inactive, South Branch ,,,
༤།༣༥༡ སྦེང་ལོར་འགྲོ་ཕན་སྨན་རྩིས་མཐོ་སླབ།,4|351,Bengaluru Men-Tse-Khang (Sowa Rigpa) College,Inactive, South Branch ,,,
༤།༡༦༧ ཧོན་སུར་འོ་མ་མཉམ་འབྲེལ།,4|167,Hunsur Gurupura Milk Producers' Co-operative Society Ltd,Inactive, South Branch ,,,
༤།༡༦༩ སྦེལ་ཀོབ་ས་གནས་རང་བདེན་ཚོགས་ཆུང་།,4|169,Bylakuppe BRDL,Inactive, South Branch ,,,
༤།༡༧༠ སྦེལ་ཀོབ་ལུགས་ཟུང་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|170,Bylakuppe Lugsung Samdupling Settlement Office,Inactive, South Branch ,,,
༤།༡༧༡ ཀོ་གལ་དོན་ལྡན་གླིང་ས་གནས་འགོ་འཛིན་ལས་ཁང་།,4|171,Kollegal Dhondenling Settlement Office,Inactive, South Branch ,,,
༤།༡༧༢ ཀོ་གལ་ས་གནས་གྲོས་ཚོགས།,4|172,Kollegal Local Assembly,Inactive, South Branch ,,,
༤།༡༩༢ སྦེང་ལོར་བོད་ཁྱིམ་སྡོད་ཤག,4|192,Bangalore TCV Youth Hostel,Inactive, South Branch ,,,
༤།༡༩༦ སྦེལ་ཀོབ་བོད་ཕྲུག་སྡོད་ཤག,4|196,Bylakuppe TCV ,Inactive, South Branch ,,,
༤།༢༡༩ སྦེང་ལོར་བོད་ཀྱི་མཐོ་སློབ་ཁང་།,4|219,Bangalore TCV College ,Inactive, South Branch ,,,
༤།༢༤༣ ཧོན་སུར་ས་གནས་འཐུས་ཚོགས།,4|243,Hunsur LTA,Inactive, South Branch ,,,
༤།༢༦༨ ༸གོང་ས་ཏ྄་ལའི་བླ་མ་སློབ་གཉེར་ཁང་གི་ཨར་པོའོ་ལས་གཞི།,4|268,Bangalore TCV College Construction,Inactive, South Branch ,,,
༤།༢༦༩ བོད་ཁྱིམ་མཉམ་སྦྲེལ།,4|269,TCV Credit Co-operative Society Ltd,Inactive, South Branch ,,,
༤།༢༧༤ སྦེལ་ཀོབ་སྤྱི་མཉམ་ཡན་ལག,4|274,FTCI Bylakuppe Branch,Inactive, South Branch ,,,
༤།༢༨༢ བདེ་སླར་རང་ཚོགས།,4|282,Bylakuppe Dickey Larsoe BRDL,Inactive, South Branch ,,,
༤།༢༨༨ ཀོ་ལེ་གྷལ་རང་ཚོགས།,4|288,Kollegal BRDL,Inactive, South Branch ,,,
༤།༢༨༩ ཧོན་སུར་རང་ཚོགས།,4|289,Hunsur BRDL,Inactive, South Branch ,,,
༤།༢༩༢ མོན་གྷོ་རང་ཚོགས།,4|292,Mundgod BRDL,Inactive, South Branch ,,,
༤།༢༩༨ སྦེང་ལོར་རང་ཚོགས།,4|298,Bangalore BRDL,Inactive, South Branch ,,,
༤།༣༡༩ མོན་གྷོ་སྃ་བྷོ་ཊ་གཞི་རིམ་བར་མ་དང་འོག་མའི་སློབ་གྲྭ།,4|319,Mundgod Tibetan Primary School (Unit of Sambhota Tibetan School),Inactive, South Branch ,,,
༤།༣༢༡ སྦེལ་ཀོབ་སྃ་བྷོ་ཊ་འབྲེལ་མཐུད་ཡིག་ཚང་།,4|321,Bylakuppe Sambhota Coordinator Office,Inactive, South Branch ,,,
༤།༣༢༢ ལྷོ་ཡན་སྨན་ཁང་ཁག་བཅུའི་སྤྱི་ཁྱབ་ཡིག་ཚང་།,4|322,South Zone 10 PHC Head Office,Inactive, South Branch ,,,
༤།༣༢༣ སྦེང་ལོར་སྨན་རྩིས་མཐོ་སླབ་ལས་གཞི།,4|323,Bangalore Mentse Khang Project,Inactive, South Branch ,,,
༤།༣༢༧ སྦེལ་ཀོབ་སྃ་བྷོ་ཊ་སློབ་གྲྭ།,4|327,Bylakuppe STS School,Inactive, South Branch ,,,
༤།༣༢༨ སྦེལ་ཀོབ་བདེ་སྐྱིད་སླར་གསོའི་སྃ་བྷོ་ཊ་སློབ་གྲྭ།,4|328,Bylakuppe Dickey Larsoe STS School,Inactive, South Branch ,,,
༤།༣༣༠ མོན་གྷོ་སྃ་བྷོ་ཊ་གཏན་ཉིན་སློབ་གྲྭ།,4|330,Mundgod STS (Camp 6),Inactive, South Branch ,,,
༤།༣༣༡ ཀོ་ལེ་གྷལ་སྃ་བྷོ་ཊ་སློབ་གྲྭ།,4|331,Kollegal Sambhota Tibetan School,Inactive, South Branch ,,,
༤།༣༣༢ སྦེལ་ཀོབ་བོད་ཕྲུག་ཁྱིམ་སྡེ་སློབ་གྲྭ།,4|332,Bylakuppe TCV School,Inactive, South Branch ,,,
༤།༣༣༣ ཧོན་སུར་སྃ་བྷོ་ཊ་ཉིན་མོའི་སློབ་གྲྭ།,4|333,Hunsur STS School,Inactive, South Branch ,,,
༥།༡ བཀའ་ཡིག་དང་བཀའ་ཤག་ཁྱབ་ཁོངས།,5|1,Kashag Secretariat (Reurring Expenses),Inactive, Head Office ,,,
༥།༢ ཆོས་རིག་ལས་ཁུངས།,5|2,Department of Religion & Culture (Reurring Expenses),Inactive, Head Office ,,,
༥།༣ ནང་སྲིད་དང་ཁྱབ་ཁོངས།,5|3,Department of Home (Reurring Expenses),Inactive, Head Office ,,,
༥།༤ དཔལ་འབྱོར་ལས་ཁུངས་དང་ཁྱབ་ཁོངས།,5|4,Department of Finance (Reurring Expenses),Inactive, Head Office ,,,
༥།༥ ཤེས་རིག་ལས་ཁུངས།,5|5,Department of Education (Reurring Expenses),Inactive, Head Office ,,,
༥།༦ བདེ་སྲུང་ལས་ཁུངས།,5|6,Department of Security (Reurring Expenses),Inactive, Head Office ,,,
༥།༧ ཕྱི་དྲིལ་དང་ཁྱབ་ཁོངས་དང་། སྐུ་ཚབ་དོན་ཁང་ཁག,5|7,Department of Information and international Relation (Reurring Expenses),Inactive, Head Office ,,,
༥།༨ ཆེས་མཐོའི་ཁྲིམས་ཞིབ་ཁང་། ཚོགས་དྲུང་ལས་ཁུངས།,5|8,Tibetan Supreme Justice Commission & Parliament Secretariat (Reurring Expenses),Inactive, Head Office ,,,
༥།༩ འདེམས་བསྐོ་ལྷན་ཁང་།,5|9,Election Commission (Reurring Expenses),Inactive, Head Office ,,,
༥།༡༠ རྩིས་ཞིབ་སྤྱི་ཁྱབ་ལས་ཁང་།,5|10,Office of the Auditor General (Reurring Expenses),Inactive, Head Office ,,,
༥།༡༡ འཕྲོད་བསྟེན་ལས་ཁུངས།,5|11,Health Department (Reurring Expenses),Inactive, Head Office ,,,
༥།༡༢ ལྡི་་ལི་དོན་གཅོད་ཁང་།,5|12,Tibet Bureau Delhi (Reurring Expenses),Inactive, Head Office ,,,
༥།༡༣ འཆར་འགོད་ལྷན་ཁང་།,5|13,Planing Commission (Reurring Expenses),Inactive, Head Office ,,,
༥།༡༤ སྣེ་ལེན་འབྲེལ་འཐུད་ཁང་།,5|14,Reception Centre (Reurring Expenses),Inactive, Head Office ,,,
༥།༡༧ འོས་བསྡུ་ལས་ཁང་།,5|17,Election Commission (Reurring Expenses),Inactive, Head Office ,,,
༥།༡༨ སུད་སི་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,5|18,Office of Tibet - Geneva Swiss (Reurring Expenses),Inactive, Head Office ,,,
༥།༡༩ ཨོ་སི་ཀྲེ་ལི་ཡ་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,5|19,Office of Tibet - Australia (Reurring Expenses),Inactive, Head Office ,,,
༥།༢༠ ཨ་རི་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,5|20,Office of Tibet - US (Reurring Expenses),Inactive, Head Office ,,,
༥།༢༡ ཐེ་ཝན་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,5|21,Office of Tibet - Taiwan (Reurring Expenses),Inactive, Head Office ,,,
༥།༢༢ དབྱིན་ལེན་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,5|22,Office of Tibet - London (UK) (Reurring Expenses),Inactive, Head Office ,,,
༥།༢༣ ཕ་རན་སི་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,5|23,Office of Tibet - France (Reurring Expenses),Inactive, Head Office ,,,
༥།༢༤ ཉི་ཧོང་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,5|24,Office of Tibet - Japan (Reurring Expenses),Inactive, Head Office ,,,
༥།༢༥ རུ་སོག་དོན་ཁང་།,5|25,Office of Tibet - Russia (Reurring Expenses),Inactive, Head Office ,,,
༥།༢༦ ལྡི་ལི་འཕགས་བོད་འབྲེལ་འཐུད་ལས་ཁང་།,5|26,Indo-Tibetan Coordination Office - Delhi (Reurring Expenses),Inactive, Head Office ,,,
༥།༢༧ ལྷོ་ཨ་ཕི་རི་ཀ་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,5|27,Office of Tibet - South Africa (Reurring Expenses),Inactive, Head Office ,,,
༥།༢༨ ལྷོ་ཨ་མི་རི་ཀ་སྐུ་ཚབ་དོན་གཅོད་ཁང་།,5|28,Office of Tibet - South America (Reurring Expenses),Inactive, Head Office ,,,
༥།༢༩ བོད་ཀྱི་སྲིད་བྱུས་ཉམས་ཞིབ་ཁང་།,5|29,Tibet Policy Institute (Reurring Expenses),Inactive, Head Office ,,,
`;

const results = [];
const lines = rawCsv.split('\n').map(l => l.trim()).filter(l => l.length > 0);

for (let i = 1; i < lines.length; i++) {
    let line = lines[i];
    let parts;
    
    // Simple CSV parser for quoted fields
    if (line.includes('"')) {
        const re = /,(?=(?:[^"]*"[^"]*")*[^"]*$)/;
        parts = line.split(re);
    } else {
        parts = line.split(',');
    }
    
    if (parts.length >= 5) {
       let tibetan_name = parts[0].trim().replace(/^"|"$/g, '').trim();
       const file_number = parts[1].trim().replace(/^"|"$/g, '').trim();
       const english_name = parts[2].trim().replace(/^"|"$/g, '').trim();
       const status = parts[3].trim().replace(/^"|"$/g, '').trim();
       const branch = parts[4].trim().replace(/^"|"$/g, '').trim();
       
       if (english_name) {
           results.push({
               tibetan_name: tibetan_name || '',
               file_number: file_number.replace(/^\|/, ''),
               name: english_name,
               is_active: status === 'Active',
               branch: branch || 'Head Office'
           });
       }
    }
}

fs.writeFileSync('public/units_seed.json', JSON.stringify(results, null, 2));
console.log('Successfully wrote ' + results.length + ' valid records with perfect Tibetan text to public/units_seed.json');
